const url = {
  dashboard: "/dashboard",
  login: "/login",
  register: "/signup",
  addCourse: "/Courses/addNewCourse",
  setting: "/Setting",
  users: "/Users",
  addCourseCategory: "/Courses/addNewCategory",
  viewCourses: "/Courses/View",
  addCourseContent: "/Courses/AddContent",
  addQuiz: "/Courses/AddQuiz",
  viewCourseContent: "/Courses/Content/View",
  home: "/Home",
  userLogin: "/User/Login",
  userSignup: "/User/Signup",
  todoList: "/User/TodoList",
  leaderBoard: "/User/LeaderBoard",
  about: "/faqs",
  contact: "/ContactUs",
  viewAllCourse: "/AllCourses",
  smartSearch: "/Search/:title/:filter",
  courseDetails: "/Courses/:title/details",
};

export default url;
